[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterMermaid = "a078cd44-4d9c-4618-b545-3ab9d77f9177"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
MacroEnergy = "260b7737-bf0e-4e84-9335-3af14438b1f5"
